### ISSUE TITLE
Support adding additional targets

### ISSUE THREAD

**Issue by dmikusa-pivotal** [paketo-community/rustup#44]
When the rustup buildpack runs, it installs the specified Rust tools. It is possible for rustup to install additional toolsets. This is helpful when cross-compiling. For buildpacks, this would be most useful to build a binary that runs on the Paketo tiny stack.

See #42 for details. 

The idea would be that after `rustup` runs for the first time, we'd look at `$BP_RUST_ADD_TOOLCHAINS` which would be a space-separated list of additional targets for `rustup` to install. We'd run `rustup target add` for each specified target.

**Comment by Ch4s3r** [comment]
Maybe consider renaming `BP_RUST_ADD_TOOLCHAINS` to `BP_RUSTUP_TARGETS`.
As this would then add a target (eg `x86_64-unknown-linux-musl`) to a specific toolchain (eg. `nightly`). See [stackoverflow](https://stackoverflow.com/questions/53210121/how-to-install-a-rust-target-for-a-specific-rustup-toolchain)

**Comment by Ch4s3r** [comment]
I think it would make sense if `BP_RUSTUP_TARGET` would only accept one target, as you'll only ever build for one target at a time?
Having a default target added in case that `musl` is activated also makes sense.
But in case `BP_RUSTUP_TARGET` is set explicitly, there should be no default musl target added?
As it would maybe add more unncessary targets?

**Comment by dmikusa-pivotal** [comment]
I ended up going with `$BP_RUST_TARGET` as we have `$BP_RUST_TOOLCHAIN` and `$BP_RUST_PROFILE`. If set, it will install the additional target. The buildpack will set this automatically if you're running on the tiny stack so that the musl target is added.
